### ISSUE TITLE
2 critical issues requesting POST DOWNLOAD API endpoint with native fetch or xhr javascript browser

### ISSUE THREAD

**Issue by chisNaN** [RTradeLtd/Temporal#365]
2 critical issues requesting POST DOWNLOAD API endpoint with native fetch or xhr javascript browser

**1) First problem concerns this endpoint url https://api.temporal.cloud/v2/ipfs/utils/download/**

fetching this url (with a valid token) and using the code from the official source available here
https://gateway.temporal.cloud/ipns/docs.api.temporal.cloud/ipfs.html#get-uploads

will return an ERR_CONTENT_LENGTH_MISMATCH 200 (OK)
(with nevertheless a 200 ok status)

but the Fetch will fail without the possibility to retrieve the blob

**2) As a "random empirical" workaround i saw a part of the official api doc where one could fetch the same endpoint thru a specific port 6767**

https://api.temporal.cloud:6767/v2/ipfs/utils/download/
in the private network session available here

https://gateway.temporal.cloud/ipns/docs.api.temporal.cloud/ipfs.html#post-download-file

it worked during a time but now it is constantly returning the following CORS errors reject:

_"has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled."_

I am pretty sure this time you will be able to reproduce the same bugs

Thanks again for your reactivity and effort in the ipfs nodes

ps: I have never had any problem with the add (upload) endpoint

**Comment by postables** [comment]
#1 is a known issue with the work around being what you're doing in step 2. I thought I updated the docs with this but I must've not pushed the update I'll do that. 

#2 you say 'in the private network session' what do you mean by this? Private networks should never be used with `api.temporal.cloud` since they are unsupported in production.

 Can you please provide sample code to trigger the issue in #2

**Comment by chisNaN** [comment]
THanks again for your reactivity

- Ok for point 1
- For point 2 i mean, in order to find this specific port 6767
I had to go in this path of the documentation
/ **Private** network usage / Post download file

I think this part of the api will need more diagnose because when i woke up this morning
it started to work again for the following browsers:

- chrome and firefox under macOS and Android

Nevertheless

- it works "randomly" with opera
- it has never worked under safari macos
(on safari it always end with a TypeError: connection lost)
**- it has also never worked for any browsers under IOS and this is very annoying IMO**

Today again at ~10h25 am gmt+1 i opened a windows 10 session in order to test under windows 10
and it started to fail on every browsers again!

But for how long?

Is there a kind of cache problem when new user agents are hitting the endpoint or something like this?

I recall i am using these sample code in the console browser from within other domain than temporal.cloud obviously

```
const token = 'a valid token'
const headers = new Headers({ 'Cache-Control': 'no-cache', Authorization: 'Bearer ' + token });
const options = { method: 'post', body: new FormData, headers };
const hash = 'existing ipfs hash'
var resp = await fetch('https://api.temporal.cloud:6767/v2/ipfs/utils/download/' + hash, options);
```

:bulb: note that in the console there is no need to wrap an await instruction in an async function (well for me it normally works without syntax error)

**Comment by postables** [comment]
Apologies for the radio silence been debugging this. I'm 99% sure this is an issue with our CORS middleware. 

Why it's happening I'm not entirely certain but I think it has to do with preflight requests not being properly handled by the middleware, and possibly something to do with the preflight request cache.

I'm testing out a fix and will hopefully have it deployed tonight.

**Comment by chisNaN** [comment]
It's ok sir 
For the moment I use a workaround by proxyfying once again thru a serverless script but this this is quite cumbersome to download twice the buffer over the network.

The weirdest thing is that the add upload endpoint to ipfs seems to NOT be affected by this cache cors problem

**Comment by postables** [comment]
@chisNaN The issues you are having should be resolved now, thanks for your patience.

**Comment by chisNaN** [comment]
Thanks for your reactivity and efforts.
It is stable on chrome, firefox macos and android
**but still not working on safari macos and neither browsers on ios**

I have made this test page on netlify so you can check with any user agent.
https://temporal-cloud-download.netlify.com
You just need to pass a valid token in the url like this 

`/?token=bla`

This page show in html the javascript code behind in case of

:bulb: For the moment i stick with the proxify solution which is working with all browsers

**Comment by xiegeo** [comment]
@chisNaN I am not able to reproduce on iOS 12.2.0, can you clear call cache and try again? If still not working, send me the request and response headers.

**Comment by postables** [comment]
Unfortunately I can't reproduce the issue with the netlify site you sent. As xiego mentioned clear your cache and try again. For any further debugging we really need the HTTP headers from your response+request otherwise there is not much else we can do.

**Comment by chisNaN** [comment]
SEEMS GOOD FOLKS
Thanks
(I forgot to say I was testing under iOS beta 13, well it will be released today...

**Comment by postables** [comment]
Thanks for your patience! If this issue crops up again open a new github issue, however it shouldn't happen again!

Cheers.

**Comment by chisNaN** [comment]
OK FOR SAFARI 13 macos now!!!
